version: "3.8"

services:
  nerfstudio:
    image: dromni/nerfstudio:${NERF_STUDIO_VER}
    container_name: nerf_studio
    ipc: host
    #    shm_size: '8gb'
    ports:
      - "7007:7007"
    working_dir: /workspace
    # These two are needed for interactive shells
#    stdin_open: true
#    tty: true

    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    env_file:
      - ./.env

    volumes:
      - C:\Users\lizas\PycharmProjects\NeRFleXGIF\.cache:/home/user/.cache
      - C:\Users\lizas\PycharmProjects\NeRFleXGIF:/workspace/
    networks:
      - NerfNetwork
#    network_mode: "host"

networks:
  NerfNetwork:
    name: nerf_net

# standalone equivalent
# docker run --gpus all -v C:\Users\lizas\PycharmProjects\NeRFleXGIF:/workspace/ -v C:\Users\lizas\PycharmProjects\NeRFleXGIF\.cache:/home/user/.cache/ -p 7007:7007 --rm -it --ipc=host dromni/nerfstudio:0.3.2